project:
  type: website
  output-dir: docs
  
website:
  title: "My 2024 Class Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/erica-faucher-142a5a266/
      - icon: github
        href: https://github.com/emf2003/my2024classwebsite
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, ERICA FAUCHER"

format:
  html:
    theme: quartz
    toc: true

editor: source

